apiVersion: v1
kind: Secret
metadata:
  name: git-user-pass
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: Karthik-Eluru
  password: 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