apiVersion: v1
kind: Service
metadata:
  labels:
    app: pipelines-dotnetcore-api
  name: pipelines-dotnetcore-api
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
      name: 6000-tcp
  selector:
    app: pipelines-dotnetcore-api
